sudo: false
language: java
jdk:
  - oraclejdk8

install: mvn -B -U dependency:go-offline test clean --quiet --fail-never -DskipTests=true
script: mvn -B -U verify --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
